name: Upload APKs to Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Download files
        run: |
          curl -O https://dl.koodoreader.com/build/app-arm64-v8a-release.apk
          curl -O https://dl.koodoreader.com/build/app-universal-release.apk
          TAG=${GITHUB_REF##*/}
          echo "Current ref tag: $TAG"
          mv app-arm64-v8a-release.apk "Koodo-Reader-$TAG-arm64.apk"
          mv app-universal-release.apk "Koodo-Reader-$TAG-universal.apk"
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: Koodo-Reader-$TAG-arm64.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: v1.7.8
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: Koodo-Reader-$TAG-universal.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: v1.7.8
